angular module 3
Dmitrii98/angular-module-3 pull request #1
Opened 2023-02-22 20:49 UTC by Dmitrii98

2023-02-23 15:49 UTC, parabolabam requested changes

2023-02-24 18:40 UTC, Dmitrii98 commented on src/app/shared/pipes/duration.pipe.ts
> +@Pipe({
could you elaborate how I could mark that, please?

2023-02-24 18:49 UTC, parabolabam commented on src/app/shared/pipes/duration.pipe.ts
> +@Pipe({
https://angular.io/api/core/Pipe#pure

2023-02-24 18:54 UTC, Dmitrii98 commented on src/app/shared/utils/field-validator.ts
> +export function fieldValidator(control: FormControl): { [key: string]: string } | null {
fixed

2023-02-24 18:54 UTC, Dmitrii98 commented on src/app/shared/components/course-form/course-form.component.html
> +          <input
fixed

2023-02-24 18:54 UTC, Dmitrii98 commented on src/app/shared/components/course-form/course-form.component.html
> +            [(ngModel)]="durationValue"
can I use the validator with ngModel?

2023-02-25 06:08 UTC, parabolabam commented on src/app/shared/components/course-form/course-form.component.html
> +            [(ngModel)]="durationValue"
It’s not forbidden at least, you can use validators, but they will be different.
There are two types of forms in angular: reactive and template based, so if you want to use ngModel then you will 💯 % stick with template driven forms and they will force you to use HTML5 internal validators as builtins and in case you need to customize validator then you’ll stick with custom directive which will force you to create additional abstraction layer which I personally would like to avoid in case it’s unnecessary 

https://angular.io/guide/forms
https://www.tektutorialshub.com/angular/custom-validator-in-template-driven-forms-in-angular/

2023-02-27 06:16 UTC, parabolabam approved these changes

2023-02-27 15:52 UTC, Dmitrii98 commented on src/app/shared/pipes/duration.pipe.ts
> +@Pipe({
fixed

2023-02-27 18:22 UTC, merged